version: "3.9"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./database/db:/data/db
      - ./database/config:/data/configdb
    userns_mode: keep-id
    expose:
      - 27017
    ports:
      - 27017:27017
  service:
    image: ghcr.io/hannahellis4242/bookmarks/bookmarks-service:latest
    restart: always
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
    expose:
      - 5001
    ports:
      - 5001:5001
volumes:
  data:
  config: